### ISSUE TITLE
没开机成功

### ISSUE THREAD

**Issue by hkk666** [sonytxl/360v6#1]
刷了你编译好的没能开机，你的设备可以开吗

**Comment by sonytxl** [comment]
我都刷不上去，准备过几天重新编译


hkk666 ***@***.***> 于 2022年9月21日周三 20:05写道：

**Comment by hkk666** [comment]
不用测试了，不存在这内核

**Comment by hkk666** [comment]
不用测试了，不存在这内核

**Comment by sendlan** [comment]
5.15的仓库不可用切换到qca的仓库去吧
